/**
 * The markdown bodies the `self` scenario publishes.
 *
 * Each one restates a finding that is written down in this repository, and each
 * one names where: an ADR under `docs/decisions/`, a source comment, or a pull
 * request description. Nothing here is a plausible-sounding review remark.
 */

const FENCE = '```'

/** ADR 0008 and the comment above `lowestCommonAncestor` in `elkLayout.ts`. */
export const CANVAS_LAYOUT_FEEDBACK = [
  '## Two things about ELK and React Flow that cost a day each',
  '',
  '### Edge sections are relative to the lowest common ancestor',
  '',
  'With `elk.hierarchyHandling: INCLUDE_CHILDREN`, ELK does **not** report edge',
  'sections relative to the container the edge was declared in. It reports them',
  'relative to the lowest common ancestor of the two endpoints. Declaring every',
  'edge on the root graph therefore does not make its coordinates absolute.',
  '',
  'Each route has to be shifted by the absolute position of that ancestor:',
  '',
  FENCE + 'ts',
  'const container = lowestCommonAncestor(parentOf, edge.source, edge.target)',
  'const origin = (container ? absolute.get(container) : undefined) ?? { x: 0, y: 0 }',
  FENCE,
  '',
  'Getting it wrong detaches every edge between two nested components from its',
  'handles by exactly the offset of the container they share — which looks like a',
  'rendering bug and is a coordinate-space bug.',
  '',
  '### `instance.fitView()` is silently dropped',
  '',
  'It schedules itself through React Flow\'s node-change queue. A fully controlled',
  'graph without `onNodesChange` never drains that queue, so the call does',
  'nothing and reports nothing. The canvas computes the viewport from the layout',
  'bounds and applies it with `setViewport` instead, which has the side benefit of',
  'making the camera a pure function of the ELK layout.',
  '',
  '- [x] edge routes shifted by the ancestor origin',
  '- [x] `setViewport` instead of `fitView`',
  '',
  'Source: `docs/decisions/0008-architecture-canvas-layout-and-edge-bundling.md`',
  'and the comment above `lowestCommonAncestor` in `frontend/src/canvas/elkLayout.ts`.',
  '',
].join('\n')

/** ADR 0004. */
export const INGESTION_VALIDATION_FEEDBACK = [
  '## Validate against the discriminator branch, not the union',
  '',
  '`IngestEventRequest` is a 20-branch `oneOf`. Validating a body against the',
  'union reports the failures of the 19 branches the agent never meant — **one bad',
  '`percent` produced about 80 errors**, none of which named the real problem.',
  '',
  'The contract carries its own `discriminator.mapping`. Selecting the single',
  'envelope schema the `type` field designates, and validating only that branch,',
  'turns the error tree into something that maps cleanly onto `errors[].field`',
  'with correct RFC 6901 pointers. The union is still the authoritative gate',
  'afterwards.',
  '',
  '## Format assertions are off by default',
  '',
  'In JSON Schema 2020-12 tooling, `format` is advisory unless assertions are',
  'switched on. With them off the backend accepted:',
  '',
  FENCE + 'json',
  '{ "clientEventId": "not-a-uuid" }',
  FENCE,
  '',
  'They are now enabled explicitly, in the backend and in the simulator.',
  '',
  'Source: `docs/decisions/0004-contract-driven-ingestion-validation.md`.',
  '',
].join('\n')

/** ADR 0002. */
export const POSITION_ALLOCATOR_FEEDBACK = [
  '## The project row is the position allocator',
  '',
  '`SELECT … FOR UPDATE` on `projects` serialises every concurrent append for that',
  'project; the next position is `last_position + 1`.',
  '',
  'The tempting alternative does not work:',
  '',
  '| Approach | Failure |',
  '| --- | --- |',
  '| `max(position) + 1` without a lock | two transactions read the same value and produce a gap or a duplicate |',
  '| `SELECT … FOR UPDATE` on the project row | concurrent appends queue; positions stay monotonic and gapless |',
  '',
  'Gapless matters beyond tidiness: the SSE cursor is the position, so',
  '`position > lastSent` is only a complete description of "what this connection',
  'still owes the client" while there are no holes.',
  '',
  'Idempotency is content based — the payload is canonicalised (keys sorted',
  'recursively, no insignificant whitespace) and hashed with SHA-256, and the',
  'canonical form is what gets stored, so column and hash always describe the same',
  'document.',
  '',
  'Source: `docs/decisions/0002-event-log-with-synchronous-projections.md`.',
  '',
].join('\n')

/** ADR 0006. */
export const REPLAY_HANDOVER_FEEDBACK = [
  '## Both obvious orderings of the replay-to-live handover are wrong',
  '',
  '1. *Read the database, then subscribe.* Everything that commits between the',
  '   last page and the subscription is delivered to nobody and is never noticed',
  '   again.',
  '2. *Subscribe, then read the database, then flush the buffer.* The overlap —',
  '   every event that is both in a page and in the buffer — is delivered twice.',
  '',
  '## What the connection does instead',
  '',
  '- **Subscribe before the first read.** From that moment every committed event',
  '  is either found by a later page or waiting in the subscription.',
  '- **Replay page by page**, advancing `lastSent`.',
  '- **After every page, drain the subscription buffer and discard it.** Sound',
  '  precisely because the publisher runs *after* the commit: an event the broker',
  '  handed out is already durable, so the next page will find it.',
  '- **End the replay only when the page was short *and* the drained buffer was',
  '  empty.** Either condition alone leaves a window.',
  '- **In the live phase, filter strictly against `lastSent`.** `Publish` is called',
  '  by the ingesting goroutine after its transaction committed, so two appends can',
  '  reach the broker in the opposite order.',
  '',
  'Source: `docs/decisions/0006-sse-replay-and-in-process-broker.md`.',
  '',
].join('\n')

/** ADR 0011. */
export const PROGRESS_SCOPE_FEEDBACK = [
  '## An overall estimate is never drawn as a counted bar',
  '',
  'Two forms, and they are not two styles of the same thing:',
  '',
  '| | Counted | Claimed |',
  '| --- | --- | --- |',
  '| Shape | discrete segments, filled from the left | no track, no fill at all |',
  '| Semantics | `role="progressbar"` with `aria-valuenow` | plain text, no ARIA value |',
  '| Marker | — | a leading `≈` that is part of the value |',
  '| Used for | `scope: own_task` **and** `basis: completed_steps` | everything else |',
  '',
  '`scope: overall_estimate` lands in the claim form **whatever basis it names**,',
  'because nothing in v0 can count the steps of a whole run: the plans are',
  'themselves reports, subagents can be spawned at any moment, and no agent knows',
  'what the others will still do. `basis` says how *that agent* arrived at its',
  'number, not that the number is checkable.',
  '',
  'The rejected alternative — one bar with the estimate in a lighter shade — reads',
  'as "the same quantity, less certain", which is precisely the sentence the',
  "contract's two scopes exist to prevent.",
  '',
  'Source: `docs/decisions/0011-run-and-agent-hierarchy.md`.',
  '',
].join('\n')

/** ADR 0012. */
export const MARKDOWN_SAFETY_FEEDBACK = [
  '## `rehype-raw` is on **on purpose**',
  '',
  'The pipeline is fixed and lives as a module constant, not assembled at the call',
  'site:',
  '',
  '`remark-parse` + `remark-gfm` → `remark-rehype` → `rehype-raw` →',
  '**`rehype-sanitize`** → React elements.',
  '',
  'Dropping raw HTML entirely would be marginally safer and would make every',
  'attack test vacuous — it would pass on a renderer whose sanitiser had rotted',
  'away years ago. With raw parsing enabled the sanitiser is the only thing',
  'between the payload and the DOM, so the tests measure the property that is',
  'actually claimed.',
  '',
  'The schema is an **allow list** taken from `hast-util-sanitize`, not a list of',
  'forbidden patterns: anything not enumerated is removed. The active element',
  'families are put in `strip`, so they go **with their children** rather than',
  'being unwrapped, and the URL protocol lists are stated explicitly.',
  '',
  '`dangerouslySetInnerHTML` appears nowhere in the inspector.',
  '',
  'Source: `docs/decisions/0012-component-inspector-and-markdown-safety.md`.',
  '',
].join('\n')

/**
 * The claim the contract made until PR #30, published early in the run and
 * corrected later. Reported as it was written, not as it turned out to be.
 */
export const PROBE_BOUNDARY_FEEDBACK = [
  '## Trust boundary of the two probes',
  '',
  '`GET /healthz` and `GET /readyz` are internal container probes. They are not',
  'routed through the Nginx frontend and are therefore not reachable from outside',
  'the Compose network, which is why the contract gives them their own internal',
  'server entry:',
  '',
  FENCE + 'yaml',
  'servers:',
  '  - url: http://backend:8080',
  '    description: Internal Go backend container — reachable only inside the Compose network',
  FENCE,
  '',
  'An agent author can rely on that boundary when reasoning about what the',
  'published port exposes.',
  '',
  'Source: `api/openapi.yaml`, paths `/healthz` and `/readyz`.',
  '',
].join('\n')

/** The corrected body, as PR #30 rewrote it after exercising the system. */
export const PROBE_BOUNDARY_FEEDBACK_CORRECTED = [
  '## Trust boundary of the two probes — corrected',
  '',
  'The statement above was wrong, and it was wrong in the direction that matters:',
  'it drew a tighter boundary than the deployment has.',
  '',
  '`frontend/nginx/default.conf.template` proxies both routes:',
  '',
  FENCE + 'nginx',
  'location = /healthz {',
  '    proxy_pass $backend;',
  '}',
  '',
  'location = /readyz {',
  '    proxy_pass $backend;',
  '}',
  FENCE,
  '',
  'curl against the published port answers `200`. Both probes are therefore',
  'reachable from outside the Compose network. They carry no project data, but',
  'like every other route in v0 they are unauthenticated.',
  '',
  'The contract now says what is true and points at the trust boundary in',
  '`docs/security-and-boundaries.md`.',
  '',
  'Source: PR #30 — "Vertrag und Einstiegspunkt an das tatsächliche Verhalten',
  'angleichen".',
  '',
].join('\n')
